=== sktrain/XML-Basis-und-XSLT/XML_Basis/ueb_xsd2/loes/buch.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Lager">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Buch" maxOccurs="unbounded">
					<xs:complexType>
						<xs:group ref="BuchGruppe"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:group name="BuchGruppe">
		<xs:sequence>
			<xs:element name="Autor" type="xs:string"/>
			<xs:element name="Titel" type="xs:string"/>
			<xs:element name="Verlag" type="xs:string"/>
			<xs:element name="Seiten" type="xs:positiveInteger"/>
			<xs:element name="Erscheinungsdatum" type="xs:date"/>
			<xs:element name="BestellNummer" type="BestellNrTyp"/>
			<xs:element name="PreisEUR">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:fractionDigits value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="BestellNrTyp">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{2}\d{5}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== sktrain/XML-Basis-und-XSLT/XML_Basis/ueb_xsd2/loes/buchhaendler.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<Lager xsi:noNamespaceSchemaLocation="buch.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Buch>
		<Autor>Hillary Rodham Clinton</Autor>
		<Titel>Gelebte Geschichte</Titel>
		<Verlag>Econ</Verlag>
		<Seiten>669</Seiten>
		<Erscheinungsdatum>2003-06-09</Erscheinungsdatum>
		<BestellNummer>XJ19151</BestellNummer>
		<PreisEUR>24.00</PreisEUR>
	</Buch>
	<Buch>
		<Autor>x</Autor>
		<Titel>x</Titel>
		<Verlag>x</Verlag>
		<Seiten>669</Seiten>
		<Erscheinungsdatum>2002-09-18</Erscheinungsdatum>
		<BestellNummer>MP19127</BestellNummer>
		<PreisEUR>8.90</PreisEUR>
	</Buch>
</Lager>
