=== sktrain/XML-Basis-und-XSLT/XML_Basis/ueb_xsd2/loes/kfz.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 
<xs:element name="AUTO">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="KFZ" maxOccurs="unbounded" >
      
        <xs:complexType>
          <xs:sequence>
            <xs:element name="HERSTELLER"  type="xs:string" />
            <xs:element name="MODELL"  type="xs:string" />

            <xs:element name="LEERGEWICHT">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:integer">
                    <xs:attribute name="einheit" type="xs:string" fixed="kg" />
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>

            <xs:element name="ZYLINDER" type="xs:integer" />

            <xs:element name="HUBRAUM">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:integer">
                    <xs:attribute name="einheit" type="xs:string" fixed="ccm" />
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>

            <xs:element name="LEISTUNG">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:integer">
                    <xs:attribute name="einheit" type="LEISTUNG_ATT_typ" default="kW" />
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
            
            <xs:element name="HOECHSTGESCHWINDIGKEIT">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:integer">
                    <xs:attribute name="einheit" type="HOECHSTGESCHWINDIGKEIT_ATT_typ" default="kmh" />
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>      
            
            
            <xs:element name="VON0AUF100">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:decimal">
                    <xs:attribute name="einheit" type="xs:string" fixed="s" />
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>         
            
          </xs:sequence>
        </xs:complexType>     

      </xs:element>
      
      
    </xs:sequence>
  </xs:complexType>
</xs:element>

<!-- Festlegen der möglichen Werte für ein Attribut -->
<xs:simpleType name="LEISTUNG_ATT_typ">
  <xs:restriction base="xs:string">
    <xs:pattern value="kW|PS"/>
  </xs:restriction>
</xs:simpleType>

<!-- Festlegen der möglichen Werte für ein Attribut -->
<xs:simpleType name="HOECHSTGESCHWINDIGKEIT_ATT_typ">
  <xs:restriction base="xs:string">
    <xs:pattern value="kmh|mph"/>
  </xs:restriction>
</xs:simpleType>



</xs:schema>

=== sktrain/XML-Basis-und-XSLT/XML_Basis/ueb_xsd2/ueb/kfz.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<AUTO xsi:noNamespaceSchemaLocation="kfz.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<KFZ>
		<HERSTELLER>BMW</HERSTELLER>
		<MODELL>BMW Z8</MODELL>
		<LEERGEWICHT einheit="kg">1690</LEERGEWICHT>
		<ZYLINDER>8</ZYLINDER>
		<HUBRAUM einheit="ccm">4941</HUBRAUM>
		<LEISTUNG einheit="kW">294</LEISTUNG>
		<HOECHSTGESCHWINDIGKEIT einheit="kmh">250</HOECHSTGESCHWINDIGKEIT>
		<VON0AUF100 einheit="s">4.7</VON0AUF100>
	</KFZ>
	<KFZ>
		<HERSTELLER>MERCEDES</HERSTELLER>
		<MODELL>SLK 32 AMG</MODELL>
		<LEERGEWICHT einheit="kg">1495</LEERGEWICHT>
		<ZYLINDER>6</ZYLINDER>
		<HUBRAUM einheit="ccm">3199</HUBRAUM>
		<LEISTUNG einheit="kW">260</LEISTUNG>
		<HOECHSTGESCHWINDIGKEIT einheit="kmh">250</HOECHSTGESCHWINDIGKEIT>
		<VON0AUF100 einheit="s">5.2</VON0AUF100>
	</KFZ>
	<KFZ>
		<HERSTELLER>AUDI</HERSTELLER>
		<MODELL>1.8 T quattro</MODELL>
		<LEERGEWICHT einheit="kg">1395</LEERGEWICHT>
		<ZYLINDER>4</ZYLINDER>
		<HUBRAUM einheit="ccm">1781</HUBRAUM>
		<LEISTUNG einheit="kW">165</LEISTUNG>
		<HOECHSTGESCHWINDIGKEIT einheit="kmh">243</HOECHSTGESCHWINDIGKEIT>
		<VON0AUF100 einheit="s">6.4</VON0AUF100>
	</KFZ>
</AUTO>
